plugins {
	id 'java'
	id 'org.springframework.boot' version '4.1.1'
	id 'io.spring.dependency-management' version '1.1.7'
	id "org.sonarqube" version "7.4.0.8496"
	id 'jacoco'
}

group = 'com.geisivan'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

dependencies {

	// Spring Boot
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-security'

	//Dotenv
	implementation 'io.github.cdimascio:java-dotenv:5.2.2'

	// JWT
	implementation 'io.jsonwebtoken:jjwt-api:0.13.0'
	runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.13.0'
	runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.13.0'

	// PostgreSQL
	runtimeOnly 'org.postgresql:postgresql'

	// OpenAPI / Swagger
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:3.1.0'

	// Lombok
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'

	// Tests
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.boot:spring-boot-webmvc-test'
	testImplementation 'org.springframework.security:spring-security-test'

	testCompileOnly 'org.projectlombok:lombok'
	testAnnotationProcessor 'org.projectlombok:lombok'

	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
	useJUnitPlatform()
	finalizedBy jacocoTestReport
}

jacocoTestReport {
	dependsOn test

	reports {
		xml.required = true
		html.required = true
	}
}

jacocoTestCoverageVerification {
	violationRules {
		rule {
			limit {
				minimum = 0.8
			}
		}
	}
}

def excludedSonar = [
		"src/main/java/com/geisivan/userservice/infrastructure/**",
		"src/main/java/com/geisivan/userservice/application/dto/**",
		"src/main/java/com/geisivan/userservice/application/mapper/**",
		"src/main/java/com/geisivan/userservice/domain/entity/**",
		"src/main/java/com/geisivan/userservice/UserServiceApplication.java",
		"src/test/java/com/geisivan/userservice/**"
]

sonar {
	properties {
		property "sonar.projectKey", "user-service"
		property "sonar.host.url", "http://localhost:9000"
		property "sonar.token", System.getenv("SONAR_TOKEN")
		property "sonar.exclusions", excludedSonar.join(",")
		property "sonar.tests", "src/test/java"
		property "sonar.java.binaries", "build/classes/java/main"
	}
}

tasks.named("sonar") {
	dependsOn tasks.jacocoTestReport
}
